# Generated by Django 5.2.1 on 2025-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=32),
        ),
    ]
