# Generated by Django 5.2.1 on 2025-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0006_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='freelance_app.skill'),
        ),
    ]
